import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./global.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen font-sans w-full">
          <h1 className="text-4xl font-bold ">Bug Demo use cache: private</h1>
          <div className="flex gap-2">
            <Link href="/" className="text-blue-500 hover:underline">
              Home
            </Link>
            <Link href="/about" className="text-blue-500 hover:underline">
              About Us
            </Link>
            <Link href="/contact" className="text-blue-500 hover:underline">
              Contact
            </Link>
            <Link href="/services" className="text-blue-500 hover:underline">
              Services
            </Link>
          </div>
          <div className="p-4 w-full">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
